{% set version = "1.3.0" %}

package:
  name: django-taggit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-taggit/django-taggit-{{ version }}.tar.gz
  sha256: 4a833bf71f4c2deddd9745924eee53be1c075d7f0020a06f12e29fa3d752732d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - django >=1.11

test:
  imports:
    - taggit
    - taggit.migrations
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://github.com/alex/django-taggit/tree/master
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-taggit is a reusable Django application for simple tagging.

extra:
  recipe-maintainers:
    - kwilcox
    - marcelotrevisani
