travis:
  secure:
    BINSTAR_TOKEN: qYvJjWfhp6jCH4RGCrOHMDoTSgJ2gBfRac+6VlXWYLTObseR4f68QwhjrwlQQfR/PQHYT4sktdF7vLmSFrxKOy+z/mupJNdWuAKz6NZJCmuf4p3rWku6U1tXepkVfS7fwRq8Vv3msVqGkkRCkJ5mmwIo5N9dA6mnSu6eGwhuNfcuKBfKVJJRZU1Ogj6OHDsNGHjGmmtl37epWwUz7lALf2dgEcr2+AsiD4fIlmCIhSPQ6nNnILsABFwbQGbQ6LxSPES1F/v4dWSn+T/OVWjEVudgKlVIsLbZkjDLVGrtwisZZmcYGeW0Alj05bl+/P2EW+JRs9xYdCpNP1zd4KO/ilWNoMNm+scz3Q8bLvMuCTmgcbjfkdjq+62g1JIk47A3ANf3cP8X+zPrjHhf1VV9jN4jE45M4TmZpnD6VZSD801+IpARTlHSNG9w7O6PMxs4Acw2yPOHPiK4XGLBKnrREPfWin6vbfpDik5Tl1ozgLoAv3wUMLI7K/nrc+QUGkYjQu7H6c3U74zgEzWDFqDia4pWqY9yfeaQUxb3EbBw99170nyV+Hiw3U2npRRaLO9qXvYP8DgaVkRF1Zuqc5vMlK9xPcupRZWm2MFTrTJbTOHgm9LaYFTYzXnWfORz/+tc6pNj1A3lM3QQP15qWmre1An5Q854/Ucqzhhspp7/lrg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
