travis:
  secure:
    BINSTAR_TOKEN: M7em801dIQw/WUJoK9hvkUHNoAixAgVcvJ/AfWtakioEFa/pXWN5Al9XsoauhS9tfCBjFt40wY9eYlv/HKZ36FliybC405w1dvTfMKz/nPLLtZB47b4WYOpnop+LNY/yLNEAv22VxfU7cN4PQi5UmMENorATrRWkd9kgo/QWxwdPCUUL0+sB7OsLi5lKyN1zU/nPfLDBH3jKfbtuFFGVuli5Vd6u3jE7EDajarnen5Y6Wk85rSFd2wB6Ed7CCaPfKgvU+bd5TLNIul2LnWLm9vnjchxwd5VqeGCXUCB02ku469h9r83ucZriOe8wET4wpQzpjp6VqYlM4GWRt5NDj8xY2d+lah+bho9v3GszZLiUdor4B9WqGoVr9nJoYd+9ZjsCet3YW8jFCRM4m5Nkr7g8PmeUdRBNhP8h9k2LO81OMTUafgmqFg6JbVweCuEAc21Yu5jvDW8/VlDgWQOApQlsVA52PllonOcJxzh9mSU5rrwPgsyEbXoPn3InhBySVzAYkk5b9WXjSSSTgwnu854svg/8SGQK77kVsPkaYmPLgBep4C7RUrjwiUyoJJkEpIxZVS3kahzzQeQvoqP4gALWiOUBJ14+xwQx2PClSQmJpDHh1/cseR455eTf7jsNvpUE5BtXErIvUsMchg7CQFeOVjNXJGizpm+cJOAh2Gw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
