travis:
  secure:
    BINSTAR_TOKEN: suWD6ab72rCQCtUsMRXA13zDbf+ezhiZswywCoAvggE+5TJFn/gn5Tr+AILFKSXwrgH3M5X3NTbfCmAT6eBzk6iN8sKRDRJtO03sP6JuoqP/cg+2QkJ1V5hH3cwtzxwsztEQhjfTAmta9nKDg52PXScJLrTelJtlxyEJ6RLoHM1HtWEGuBGHPTw4zjfx5V9F8gadT7/Qwloje5Ve75Kg/zCEPAlhAYr2nwVl04HR/VhYxLqM3TTxi1EIfRLHEHwgQipYcADrfDciCGf27+l32y7NcxzPDohmbdvORt+nTzoEOlIcAl5aYhZ+DPOYQz+OheHHyw5erZp2qpjrBF8DVa5Zdjs4iTOTN3iI+hcULsOgCMv36cwcktuJziktsErM6xsmLQn+LrWCsea0C/HPWQVMwTjLjOGdAvaHFaro+K/djRZBPobgGM1wQK+zYrDIT+k9HZ3izr1nIiXVmHkMxBfF6vNaQMbLLQd5Q41Vv+A7NKk7fUAWqIuSoVGiXcbOm7ag941LqO09RFXMwTtUqv5YwmwEwJEdjlPG1qouY4WwU6SQAD0p580g8N+UA01yIWorDLbuEoJf6DQxPQoVckkU4IzcHeZc2M1bI+UbD1fiKKkyu7AkRTCMYBZc5Uuc55jflvu7700FuPoqKT/vo2LRPBSGVN7WyXdgYvU+QRM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
